spring.datasource.url=jdbc:mysql://mysql:3306/studentdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=ton_mot_de_passe
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Server configuration
server.port=8082
server.servlet.context-path=/student
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
